"""add user

Revision ID: 15a519ee183f
Revises: 
Create Date: 2024-09-03 17:16:19.294047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a519ee183f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pinyin', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.String(length=1024), nullable=False),
    sa.Column('accessToken', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
