"""add user data

Revision ID: 197a61352aaf
Revises: 
Create Date: 2024-09-03 21:08:49.156571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197a61352aaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('seiueID', sa.Integer(), nullable=False),
    sa.Column('eduID', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pinyin', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.String(length=1024), nullable=False),
    sa.Column('accessToken', sa.String(length=1024), nullable=False),
    sa.Column('accessTokenExpires', sa.DateTime(), nullable=False),
    sa.Column('refreshToken', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('seiueID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
