'''reschedules

Revision ID: df40b00b8328
Revises: ce5f8a9297f8
Create Date: 2024-09-28 22:00:39.057431

'''
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df40b00b8328'
down_revision: Union[str, None] = 'ce5f8a9297f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reschedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day', sa.String(length=15), nullable=False),
    sa.Column('day_target', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reschedules')
    # ### end Alembic commands ###
