'''add rooms and activities

Revision ID: f1c4fb0f34cb
Revises: 197a61352aaf
Create Date: 2024-09-04 07:53:38.836806

'''
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c4fb0f34cb'
down_revision: Union[str, None] = '197a61352aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('endTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roomactivities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roomId', sa.String(length=4), nullable=False),
    sa.Column('periodId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['periodId'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roomId'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomactivities')
    op.drop_table('rooms')
    op.drop_table('periods')
    # ### end Alembic commands ###
